form_opendata/urls.py
from django.urls import path
from django.conf.urls.static import static
import os
from django.conf import settings
from . import views 

urlpatterns = [
    path('', views.form_opendata, name='form_opendata'),
    path('review/', views.review_metadata, name='review_metadata'),
    path('submit/', views.submit_metadata, name='submit_metadata'),
    path('view_json/<str:filename>/', views.view_json, name='view_json'),
    path('serve_json/<str:filename>/', views.serve_json_file, name='serve_json_file'),
] 

metadata/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    #path('admin/', admin.site.urls),
    path('projectmetadata/', include('form_opendata.urls'))
]

form_opendata/models.py
from django.db import models

# Create your models here.

form_opendata/forms.py
from django import forms

class MetadataForm(forms.Form):
   project_name = forms.CharField(max_length=100, required=True, label="Project Name", initial="")
   authors = forms.CharField(widget=forms.Textarea(attrs={'rows': 3}), required=True, label="Authors", help_text="Enter authors separated by commas", initial="")
   description = forms.CharField(widget=forms.Textarea(attrs={'rows': 5}), required=True, label="Description", initial="")
   url_name = forms.CharField(label='URL Name', max_length=100, required=True, initial="")
   project_codes = forms.CharField(widget=forms.Textarea(attrs={'rows': 3}), required=False, label="Project Codes", help_text="Enter project codes separated by commas", initial="")

form_opendata/views.py
import os
import json
import uuid
from django.shortcuts import render, redirect
from .forms import MetadataForm
from django.conf import settings
from django.http import JsonResponse, Http404
from django.urls import reverse

# Create your views here.
#def form_opendata(request):
#    return render(request, 'form_opendata.html')


def form_opendata(request):
    if request.method == 'POST':
        form = MetadataForm(request.POST)
        if form.is_valid():
            # Clean authors and project codes by removing empty items caused by double commas
            authors = [author.strip() for author in form.cleaned_data['authors'].split(',') if author.strip()]
            project_name = form.cleaned_data['project_name']
            description = form.cleaned_data['description']
            url_name = form.cleaned_data['url_name']  # Capture URL Name
            project_codes = [code.strip() for code in form.cleaned_data['project_codes'].split(',') if code.strip()]
            project_uuid = str(uuid.uuid4())

            metadata = {
                "uuid": project_uuid,
                "authors": authors,
                "projectName": project_name,
                "Description": description,
                "url_name": url_name,  # Store URL Name in metadata
                "license": {
                    "so:name": "toronto",
                    "so:url": "https://www.nature.com/articles/461168a#Sec2"
                },
                "project_codes": project_codes,
                "so:url": f"https://opendata.earlham.ac.uk/wheat/under_license/toronto/{url_name}/",
                "irods_path": f"/grassrootsZone/public/under_license/toronto/{url_name}",
                "@type": "Grassroots:Project",
                "type_description": "Dataset",
                "so:image": "https://grassroots.tools/grassroots/images/aiss/drawer"
            }

            # Custom fields handling (not added to JSON yet)
            custom_fields = {}
            for key, value in request.POST.items():
                if key.startswith('custom_field_') and value:
                    field_num = key.split('_')[-1]
                    custom_value_key = f'custom_value_{field_num}'
                    if custom_value_key in request.POST:
                        custom_fields[value] = request.POST[custom_value_key]


            # Save metadata to session for review
            request.session['metadata'] = metadata
            request.session['custom_fields'] = custom_fields

            return redirect('review_metadata')
    else:
        form = MetadataForm()

    return render(request, 'form_opendata.html', {'form': form})



def review_metadata(request):
    metadata = request.session.get('metadata')
    custom_fields = request.session.get('custom_fields', {})
    
    if not metadata:
        return redirect('form_opendata')

    if request.method == 'POST':
        form = MetadataForm(request.POST)
        if form.is_valid():
            # Clean and strip whitespace, and filter out empty items
            cleaned_authors = [author.strip() for author in form.cleaned_data['authors'].split(',') if author.strip()]
            cleaned_project_codes = [code.strip() for code in form.cleaned_data['project_codes'].split(',') if code.strip()]
            cleaned_description = form.cleaned_data['description'].replace('\r\n', ' ').replace('\n', ' ').strip()
            url_name = form.cleaned_data['url_name'].strip()

            # Update the session with the cleaned data, keeping the original structure intact
            metadata.update({
                'projectName': form.cleaned_data['project_name'],
                'url_name': url_name,  # Update URL name in metadata
                'authors': cleaned_authors,
                'Description': cleaned_description,
                'project_codes': cleaned_project_codes,
                # Update the URLs with the new url_name value
                'so:url': f"https://opendata.earlham.ac.uk/wheat/under_license/toronto/{url_name}/",
                'irods_path': f"/grassrootsZone/public/under_license/toronto/{url_name}",
            })

            # Save the updated metadata back to the session
            request.session['metadata'] = metadata

            # Update custom fields in the session
            custom_fields_updated = {}
            for key, value in request.POST.items():
                if key.startswith('custom_field_') and value:
                    field_num = key.split('_')[-1]
                    custom_value_key = f'custom_value_{field_num}'
                    if custom_value_key in request.POST:
                        custom_fields_updated[value] = request.POST[custom_value_key]
            request.session['custom_fields'] = custom_fields_updated
            
            return redirect('submit_metadata')
    else:
        # Prepopulate the form with current metadata
        form = MetadataForm(initial={
            'project_name': metadata.get('projectName', ''),
            'url_name': metadata.get('url_name', ''),
            'authors': ', '.join(metadata.get('authors', [])),
            'description': metadata.get('Description', ''),
            'project_codes': ', '.join(metadata.get('project_codes', [])),
        })

    return render(request, 'review_metadata.html', {'form': form, 'custom_fields': custom_fields})







def submit_metadata(request):
    metadata = request.session.get('metadata')
    custom_fields = request.session.get('custom_fields', {})
    if not metadata:
        return redirect('form_opendata')

    # Clean up any remaining whitespace
    metadata['authors'] = [author.strip() for author in metadata['authors']]
    metadata['project_codes'] = [code.strip() for code in metadata['project_codes']]
    metadata['Description'] = metadata['Description'].replace('\r\n', ' ').replace('\n', ' ').strip()

    # Remove the url_name from the final metadata
    url_name = metadata.pop('url_name', None)
    project_name = metadata['projectName']
    sanitized_url_name = url_name.replace(' ', '_') if url_name else project_name.replace(' ', '_')

    # Sanitize custom field names (replace spaces with underscores)
    sanitized_custom_fields = {key.replace(' ', '_'): value for key, value in custom_fields.items()}

    #merge custom fields into metadata
    metadata.update(sanitized_custom_fields)

    # Save JSON file using url_name instead of project_name
    json_output_path = os.path.join(settings.JSON_OUTPUT_DIR, f'{sanitized_url_name}.json')
    
    # Ensure the JSON_OUTPUT folder exists
    if not os.path.exists(settings.JSON_OUTPUT_DIR):
        os.makedirs(settings.JSON_OUTPUT_DIR)

    # Save JSON file in the JSON_OUTPUT folder
    with open(json_output_path, 'w') as json_file:
        json.dump(metadata, json_file, indent=4)

    #generate and save the Python script to apply metadata to iRODS
    python_script_output_path = os.path.join(settings.JSON_OUTPUT_DIR, f'{sanitized_url_name}_irods_script.py')
    python_script_content = generate_irods_script(metadata)
    with open(python_script_output_path, 'w') as python_script_file:
        python_script_file.write(python_script_content)


    del request.session['metadata']
    del request.session['custom_fields']

    # Since the JSON_OUTPUT directory is not accessible via a direct URL, we'll use the 'serve_json_file' view to serve the file
    json_url = reverse('serve_json_file', args=[sanitized_url_name])
    view_json_url = reverse('view_json', args=[sanitized_url_name])

    return render(request, 'submitted.html', {'json_url': json_url, 'view_json_url': view_json_url})



def view_json(request, filename):
    # Construct the path to the JSON file in JSON_OUTPUT directory
    json_path = os.path.join(settings.JSON_OUTPUT_DIR, f'{filename}.json')
    
    # Check if the file exists
    if not os.path.exists(json_path):
        raise Http404("JSON file not found")

    # Generate the URL to fetch the JSON using serve_json_file
    json_url = reverse('serve_json_file', args=[filename])

    return render(request, 'view_json.html', {'json_url': json_url})


def serve_json_file(request, filename):
    json_path = os.path.join(settings.JSON_OUTPUT_DIR, f'{filename}.json')

    if not os.path.exists(json_path):
        raise Http404("JSON file not found")

    try:
        with open(json_path, 'r') as json_file:
            data = json.load(json_file)
    except json.JSONDecodeError:
        raise Http404("Error decoding JSON file")

    return JsonResponse(data)


def generate_irods_script(metadata):
    # Extract required fields from metadata
    uuid = metadata['uuid']
    authors = ', '.join(metadata['authors'])
    description = metadata['Description']
    license_name = metadata['license']['so:name'].capitalize()
    license_url = metadata['license']['so:url']
    project_name = metadata['projectName']
    irods_path = metadata['irods_path']

    # Generate the Python script content
    script_content = f"""
import json
from irods.session import iRODSSession
from irods.meta import iRODSMeta
from irods.exception import CollectionDoesNotExist

# iRODS connection parameters
IRODS_HOST = 'opendata-dsw'
IRODS_PORT = 1247
IRODS_USER = 'grassroots'
IRODS_PASS = '<removed>'
IRODS_ZONE = 'grassrootsZone'

# Target iRODS collection path
target_collection_path = "{irods_path}"

def apply_metadata(path, metadata, session):
    # Extract and add the specific metadata attributes
    attributes = [
        ('authors', "{authors}"),
        ('description', "{description}"),
        ('license', "{license_name}"),
        ('license_url', "{license_url}"),
        ('projectName', "{project_name}"),
        ('uuid', "{uuid}")
    ]

    try:
        coll = session.collections.get(path)
        for attribute, value in attributes:
            if value:  # Only add metadata if the value is not empty
                meta = iRODSMeta(attribute, value)
                coll.metadata.add(meta)

form_opendata/templates/form_opendata.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Capture Metadata{% endblock %}

{% block all_styles_and_scripts %}
    {{ block.super }}
    <style>
        body {
            padding-top: 110px;
        }
        .form-group {
            margin-bottom: 1.5rem;
        }
        .form-label {
            margin-bottom: .5rem;
        }
        .form-control.is-invalid {
            border-color: #dc3545;
        }
        .invalid-feedback {
            display: block;
        }
        .submit-button {
            margin-bottom: 2rem; /* Add space below the submit button */
        }
        .custom-fields-section {
            margin-top: 20px;
            margin-bottom: 20px; /* Add some space between the custom fields and the submit button */
        }
        .remove-field {
            cursor: pointer;
            color: red;
            margin-left: 10px;
        }
    </style>
{% endblock %}

{% block content %}
<div class="container mt-5">
    <h1>Capture Metadata</h1>
    <form method="post" class="mt-4">
        {% csrf_token %}
        <div class="form-group">
            <label for="id_project_name" class="form-label">Project Name</label>
            <input type="text" name="project_name" id="id_project_name" class="form-control{% if form.project_name.errors %} is-invalid{% endif %}" value="{{ form.project_name.value|default_if_none:'' }}">
            {% for error in form.project_name.errors %}
                <div class="invalid-feedback">{{ error }}</div>
            {% endfor %}
        </div>
        <div class="form-group">
            <label for="id_authors" class="form-label">Authors</label>
            <textarea name="authors" id="id_authors" class="form-control{% if form.authors.errors %} is-invalid{% endif %}" rows="3">{{ form.authors.value|default_if_none:'' }}</textarea>
            <small class="form-text text-muted">Enter authors separated by commas</small>
            {% for error in form.authors.errors %}
                <div class="invalid-feedback">{{ error }}</div>
            {% endfor %}
        </div>
        <div class="form-group">
            <label for="id_description" class="form-label">Description</label>
            <textarea name="description" id="id_description" class="form-control{% if form.description.errors %} is-invalid{% endif %}" rows="5">{{ form.description.value|default_if_none:'' }}</textarea>
            {% for error in form.description.errors %}
                <div class="invalid-feedback">{{ error }}</div>
            {% endfor %}
        </div>
        <div class="form-group">
            <label for="id_url_name" class="form-label">
                URL Name
                <small class="text-muted" style="font-size: 0.9em;">(Usually a name, date and key words: <strong>Smith_2024_30_01_paragon_v1</strong>)</small>
            </label>
            <input type="text" name="url_name" id="id_url_name" 
                   class="form-control{% if form.project_name.errors %} is-invalid{% endif %}" 
                   value="{{ form.url_name.value|default_if_none:'' }}" autocomplete="off">
        
            <!-- Add an explanation below the input field -->
            <small class="form-text text-muted">
                The URL for your project will be: 
                <span id="url_preview">https://opendata.earlham.ac.uk/wheat/under_license/toronto/<strong>&lt;URL_name&gt;</strong></span>
            </small>
        
            {% for error in form.url_name.errors %}
                <div class="invalid-feedback">{{ error }}</div>
            {% endfor %}
        </div>
        <div class="form-group">
            <label for="id_project_codes" class="form-label">Project Codes</label>
            <textarea name="project_codes" id="id_project_codes" class="form-control{% if form.project_codes.errors %} is-invalid{% endif %}" rows="3">{{ form.project_codes.value|default_if_none:'' }}</textarea>
            <small class="form-text text-muted">Enter project codes separated by commas</small>
            {% for error in form.project_codes.errors %}
                <div class="invalid-feedback">{{ error }}</div>
            {% endfor %}
        </div>

       <!-- Custom Fields Section -->
       <div class="custom-fields-section">
        <h5>Additional Custom Fields</h5>
        <div id="custom-fields-container"></div>
        <button type="button" class="btn btn-secondary" id="add-custom-field-btn">Add Custom Field</button>
       </div> 

        <button type="submit" class="btn btn-primary  submit-button">Submit</button>
    </form>
</div>

<script>
    document.getElementById('add-custom-field-btn').addEventListener('click', function () {
        const container = document.getElementById('custom-fields-container');
        const fieldCount = container.children.length;

        const newField = document.createElement('div');
        newField.className = 'form-group';
        newField.innerHTML = `
            <label for="custom_field_${fieldCount}" class="form-label">Custom Field ${fieldCount + 1}</label>
            <input type="text" name="custom_field_${fieldCount}" id="custom_field_${fieldCount}" class="form-control" placeholder="Enter field name">
            <input type="text" name="custom_value_${fieldCount}" id="custom_value_${fieldCount}" class="form-control mt-2" placeholder="Enter field value">
            <span class="remove-field" onclick="removeField(this)">Remove</span>
        `;
        container.appendChild(newField);
    });

    function removeField(element) {
        element.parentElement.remove();
    }
</script>

<script>
    document.getElementById('id_url_name').addEventListener('input', function() {
        var urlName = this.value.trim(); // Get the input value
        var urlPreview = document.getElementById('url_preview');
        
        if (urlName) {
            urlPreview.innerHTML = 'https://opendata.earlham.ac.uk/wheat/under_license/toronto/' + urlName;
        } else {
            urlPreview.innerHTML = 'https://opendata.earlham.ac.uk/wheat/under_license/toronto/<strong>&lt;URL_name&gt;</strong>';
        }
    });
</script>
{% endblock %}

form_opendata/templates/review_metadata.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Review Metadata{% endblock %}

{% block all_styles_and_scripts %}
    {{ block.super }}
    <style>
        body {
            padding-top: 110px;
        }

        .submit-button {
            margin-bottom: 2rem; /* Add space below the submit button */
        }
        .custom-field-name {
            width: 60%; /* Adjust the width as needed */
        }
    </style>
{% endblock %}

{% block content %}
<div class="container mt-5">
    <h1>Review Metadata</h1>
    <form method="post" action="{% url 'review_metadata' %}">
        {% csrf_token %}
        <table class="table table-striped mt-4">
            <tr>
                <th>Project Name</th>
                <td>
                    <input type="text" name="project_name" id="id_project_name" class="form-control" value="{{ form.project_name.value|default_if_none:'' }}">
                </td>
            </tr>
            <tr>
                <th>Authors</th>
                <td>
                    <textarea name="authors" id="id_authors" class="form-control" rows="3">{{ form.authors.value|default_if_none:'' }}</textarea>
                    <small class="form-text text-muted">Enter authors separated by commas</small>
                </td>
            </tr>
            <tr>
                <th>Description</th>
                <td>
                    <textarea name="description" id="id_description" class="form-control" rows="5">{{ form.description.value|default_if_none:'' }}</textarea>
                </td>
            </tr>
            <tr>
                <th>URL Name</th>
                <td>
                    <input type="text" name="url_name" id="id_url_name" class="form-control" value="{{ form.url_name.value|default_if_none:'' }}">
                </td>
            </tr>
            <tr>
                <th>Project Codes</th>
                <td>
                    <textarea name="project_codes" id="id_project_codes" class="form-control" rows="3">{{ form.project_codes.value|default_if_none:'' }}</textarea>
                    <small class="form-text text-muted">Enter project codes separated by commas</small>
                </td>
            </tr>
             <!-- Custom fields: name on the left, value on the right, both editable -->
             {% if custom_fields %}
             <tr>
                 <th colspan="2">Custom Fields</th>
             </tr>
             {% for field_name, field_value in custom_fields.items %}
                 <tr>
                     <th>
                         <input type="text" name="custom_field_{{ forloop.counter }}" value="{{ field_name }}" class="form-control custom-field-name">
                     </th>
                     <td>
                         <input type="text" name="custom_value_{{ forloop.counter }}" value="{{ field_value }}" class="form-control">
                     </td>
                 </tr>
             {% endfor %}
         {% endif %}


        </table>
        <button type="submit" class="btn btn-primary submit-button">Update Metadata</button>
    </form>
</div>
{% endblock %}

form_opendata/templates/submitted.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Metadata Submitted{% endblock %}

{% block all_styles_and_scripts %}
    {{ block.super }}
    <style>
        body {
            padding-top: 110px;
        }
        
    </style>
{% endblock %}

{% block content %}
<div class="container mt-5">
    <h1>Metadata Submitted Successfully!</h1>
    <p>Your metadata has been successfully captured and saved.</p>
    <p>You can view the JSON file below:</p>
    <ul>
        <li><a href="{{ view_json_url }}" target="_blank">View JSON File (Formatted)</a></li>        
    </ul>
    <p><a href="{% url 'form_opendata' %}" class="btn btn-primary">Submit Another Entry</a></p>
</div>
{% endblock %}

form_opendata/templates/view_json.html
{% extends 'base.html' %}
{% load static %}

{% block title %}View JSON{% endblock %}

{% block content %}
<div class="container mt-5">
    <h1>Formatted JSON View</h1>
    <pre id="json-output" style="background-color: #f5f5f5; padding: 15px; border-radius: 5px; white-space: pre-wrap;"></pre>
</div>

<script>
    // Fetch the JSON file and format it for display
    fetch("{{ json_url }}")
        .then(response => response.json())
        .then(json => {
            document.getElementById("json-output").textContent = JSON.stringify(json, null, 4);
        })
        .catch(error => {
            console.error("Error loading JSON:", error);
            document.getElementById("json-output").textContent = "Error loading JSON.";
        });
</script>
{% endblock %}